name: Test

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    env:
      IMAGE_NAME: foo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        docker build -t docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${GITHUB_REF##*/} .
