name: Test

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    env:
      IMAGE_NAME: foo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm/v7
        push: true
        tags: foo:1
